src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your title must be at least {{ limit }} characters long",
     *      maxMessage = "Your title cannot be longer than {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @Assert\Type(
     *     type="float",
     *     message="The value {{ value }} is not a valid {{ float }}."
     * )
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @Assert\Url(
     *    message = "The url '{{ value }}' is not a valid url",
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="product")
     */
    private $reviews;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="products")
     */
    private $user;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getProduct() === $this) {
                $review->setProduct(null);
            }
        }

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $body;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $product;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mock_user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getMockUser(): ?string
    {
        return $this->mock_user;
    }

    public function setMockUser(string $mock_user): self
    {
        $this->mock_user = $mock_user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('price')
            // ->add('image')
            ->add('image_File', FileType::class, [
                'label' => ' ',
                // 'attr' => array('hidden' => "true"),
                
                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // everytime you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/gif',
                            'image/bmp',
                            'image/svg+xml'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/api/ProductController.php
<?php

namespace App\Controller\api;

use App\Entity\Product;
use App\Entity\Review;
use App\Repository\ProductRepository;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\ImageUploader;

class ProductController extends AbstractController
{
    /**
     * @Route("/api/products", name="ApiProducts")
     */
    public function getProducts(ProductRepository $repo)
    {
        $products = $repo->findAll();
        return $this->json(["products" => $products, "user" => $this->getUser()]);
    }
    /**
     * @Route("/api/product/{id}", name="ApiGetProduct", methods={"GET"})
     */
    public function getProduct(Product $product)
    {
        return $this->json(["product" => $product]);
    }
    /**
     * @Route("/api/product", name="ApiNewProduct", methods={"POST"})
     */
    public function newProduct(Request $request, ObjectManager $manager, ImageUploader $imageUploader)
    {
        $req = $request->request;
        $product = new Product;
        $product->setUser($this->getUser());
        if (
            !$req->get('title')
            & !$req->get('description')
            & !$req->get('price')
            & !$req->get('image')
            & !$request->files->get("image_file")
        ) {
            return $this->json("please send some data");
        }
        if ($req->get('title')) {
            $product->setTitle($req->get('title'));
        } else {
            $product->setTitle("no title");
        }
        if ($req->get('description')) {
            $product->setDescription($req->get('description'));
        } else {
            $product->setDescription("no description");
        }
        if ($req->get('price')) {
            $product->setPrice($req->get('price'));
        } else {
            $product->setPrice(0);
        }
        if ($req->get('image')) {
            $product->setImage($req->get('image'));
        } else if ($request->files->get("image_file")) {
            $imageFile = $request->files->get("image_file");
            $fileName = $imageUploader->upload($imageFile);
            $product->setImage($fileName);
        } else {
            $product->setImage("/uploads/images/products/no_image_to_show_-5d9fa1b8ad3ae.webp");
        }

        $manager->persist($product);
        $manager->flush();

        return $this->json($product);
    }
    /**
     * @Route("/api/product/edit/{id}", name="ApiUpdateProduct", methods={"POST"})
     */
    public function updateProduct(Product $product, Request $request, ObjectManager $manager, ImageUploader $imageUploader)
    {
        if ($this->getUser() !== $product->getUser()) {
            return $this->json(["code"=> 401, 'message' => 'not authorized'], 401);
        }
        $req = $request->request;
        if (
            !$req->get('title')
            & !$req->get('description')
            & !$req->get('price')
            & !$req->get('image')
            & !$request->files->get("image_file")
        ) {
            return $this->json("please send some data to modify");
        }
        if ($req->get('title')) {
            $product->setTitle($req->get('title'));
        }
        if ($req->get('description')) {
            $product->setDescription($req->get('description'));
        }
        if ($req->get('price')) {
            $product->setPrice($req->get('price'));
        }
        if ($req->get('image')) {
            $product->setImage($req->get('image'));
        } else if ($request->files->get("image_file")) {
            $imageFile = $request->files->get("image_file");
            $fileName = $imageUploader->upload($imageFile);
            $product->setImage($fileName);
        } else {
            $product->setImage("/uploads/images/products/no_image_to_show_-5d9fa1b8ad3ae.webp");
        }
        $manager->flush();
        return $this->json($product);
    }
    /**
     * @Route("/api/product/{id}", name="ApiDeleteProduct", methods={"DELETE"})
     */
    public function deleteProduct(Product $product, ObjectManager $manager)
    {
        if ($this->getUser() !== $product->getUser()) {
            return $this->json('not authorized', 401);
        }
        $manager->remove($product);
        $manager->flush();

        return $this->redirectToRoute('products');
    }
    /**
     * @Route("/api/product/{id}/review/add", name="ApiAddReview", methods={"POST"})
     */
    public function addProductReview(Product $product, Request $request, ObjectManager $manager)
    {
        if (!$this->getUser()) {
            return $this->json(["code"=> 401, 'message' => 'not authorized'], 401);
        }
        $req = $request->request;
        $review = new Review();
        $review->setUser($this->getUser());
        $review->setMockUser('mock User');
        $review->setProduct($product);
        $review->setCreatedAt(new \DateTime());

        $review->setBody($req->get('body'));
        $review->setRating($req->get('rating'));

        $manager->persist($review);
        $manager->flush();

        return $this->json($review);
    }
    /**
     * @Route("/api/product/review/delete/{id}", name="ApiDeleteProductReview", methods={"DELETE"})
     */
    public function deleteProductReview(Review $review, ObjectManager $manager)
    {
        if ($this->getUser() !== $review->getUser()) {
            return $this->json(["code"=> 401, 'message' => 'not authorized'], 401);
        }
        $manager->remove($review);
        $manager->flush();

        return $this->json('review deleted');
    }
}

src/Controller/web/ProductController.php
<?php

namespace App\Controller\web;

use App\Entity\Product;
use App\Entity\Review;
use App\Form\ProductReviewType;
use App\Form\ProductType;
use App\Repository\ProductRepository;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\ImageUploader;

class ProductController extends AbstractController
{
    /**
     * @Route("/products", name="products")
     */
    public function getProducts(ProductRepository $repo)
    {
        $products = $repo->findAll();
        return $this->render("product/products.html.twig", ["products" => $products]);
    }
    /**
     * @Route("/product/{id}", name="getProduct", methods={"POST","GET"})
     */
    public function getProduct(Product $product = null, Request $request, ObjectManager $manager)
    {
        if (!$product) {
            return $this->redirectToRoute('products');
        }
        // add Review 
        $review = new Review();
        $form = $this->createForm(ProductReviewType::class, $review);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $review = $form->getData();
            $review->setMockUser('mock User');
            $review->setUser($this->getUser());
            $review->setProduct($product);
            $review->setCreatedAt(new \DateTime());

            $manager->persist($review);
            $manager->flush();

            $review = new Review();
            $form = $this->createForm(ProductReviewType::class, $review);
        }
        return $this->render("product/product.html.twig", ["product" => $product, 'form' => $form->createView()]);
    }
    /**
     * @Route("/products/new", name="newProduct", methods={"POST","GET"})
     * @Route("/product/edit/{id}", name="updateProduct", methods={"POST","GET"})
     */
    public function submitProduct(Product $product = null, Request $request, ObjectManager $manager, ImageUploader $imageUploader)
    {
        if ($product) {
            if ($product->getUser() !== $this->getUser()) {
                return $this->redirectToRoute('products');
            }
        }
        if (!$product) {
            $product = new Product();
            $product->setUser($this->getUser());
        }

        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $product = $form->getData();
            if ($form['image_File']->getData()) {
                $imageFile = $form['image_File']->getData();
                $fileName = $imageUploader->upload($imageFile);
                $product->setImage($fileName);
            }
            if (!$product->getImage()) {
                $product->setImage("/uploads/images/products/no_image_to_show_-5d9fa1b8ad3ae.webp");
            };

            $manager->persist($product);
            $manager->flush();

            return $this->redirectToRoute('products');
        }
        return $this->render('product/submit.html.twig', array(
            'form' => $form->createView(),
            'isEdit' => $product->getId() !== null,
        ));
    }

    /**
     * @Route("/product/{id}", name="deleteProduct", methods={"DELETE"})
     */
    public function deleteProduct(Product $product, ObjectManager $manager)
    {
        if ($this->getUser() !== $product->getUser()) {
            return $this->json('not authorized', 401);
        }
        $manager->remove($product);
        $manager->flush();
        return $this->json('product deleted');
    }
    /**
     * @Route("/product/review/delete/{id}", name="deleteProductReview", methods={"DELETE"})
     */
    public function deleteProductReview(Review $review, ObjectManager $manager)
    {
        if ($this->getUser() !== $review->getUser()) {
            return $this->json('not authorized', 401);
        }
        $manager->remove($review);
        $manager->flush();
        return $this->json('review deleted');
    }
}

templates/product/edit.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="row mb-2">
        <button type="button" onclick="window.history.back();" class="btn btn-secondary btn-sm btn-block mx-3">go back</button>
    </div>
    {{form_start(form)}}
    {{form_row(form.title, {"attr" : {"class" : "form-control mb-2"}})}}
    {{form_row(form.description, {"attr" : {"class" : "form-control mb-2"}})}}
    {{form_row(form.price, {"attr" : {"class" : "form-control mb-2"}})}}
    {{form_row(form.image, {"attr" : {"class" : "form-control mb-2"}})}}
    <button type="submit" name="submit" id="submit" class="btn btn-block {% if isEdit %} btn-warning {% else %}btn-primary{% endif %}">
        {% if isEdit %}
            Edit product
        {% else %}
            Add product
        {% endif %}
    </button>
    {{form_end(form)}}

{% endblock %}

templates/product/product.html.twig
{% extends "base.html.twig" %}
{% block title %}
    {{product.title}}
{% endblock %}
{% block body %}
    <div class="row">
        <button type="button" onclick="window.history.back();" class="btn btn-secondary btn-block">go back</button>
    </div>    
    {# show post #}
    <div class="row mt-3">
        <div class="card">
            <div class="card-body text-center">
                <img src="{{product.image}}?{{product.price}}" class="img-fluid mb-2" alt="{{product.title}}" style="max-width: 50%;">
                <h4 class="card-title">{{product.title}}</h4>
                <p class="card-text">{{product.description}}</p>
                <p class="card-text">{{product.price}}
                    $</p>
                {% if app.user and product.user == app.user %}
                    <button onclick="deleteProduct({{product.id}})" class="btn btn-danger btn-sm">Delete</button>
                    <button onclick="location.href ='edit/{{product.id}}'" class="btn btn-warning btn-sm mx-2">Edit</button>
                {% endif %}
                    <button onclick="location.href='/cart/add/{{product.id}}'"  class="btn btn-warning btn-sm my-3 btn-block">add to cart 🛒</button>
                
            </div>
        </div>
    </div>
    {# add comment review #}
    {% if app.user %}
        <div class="row mt-3">
            <div class="card text-left" style="width: 100%;">
                <div class="card-body">
                    <h4 class="card-title">Write a Review</h4>
                    {{form_start(form)}}
                    {{form_row(form.rating, {"attr" : {"class" : "form-control mb-2"}})}}
                    {{form_row(form.body, {"attr" : {"class" : "form-control mb-2"}})}}
                    <button type="submit" class="btn btn-primary btn-block">
                        Add your Review
                    </button>
                    {{form_end(form)}}
                </div>
            </div>
        </div>
    {% else %}
        <div class="row mt-3">
            <div class="alert alert-warning text-center" style="width: 100%;" role="alert">
                <a href="/login">
                <strong>login to make a comment </strong>
                </a>
            </div>
        </div>
    {% endif %}
    {# show reviews and comments #}
    <div class="row mt-3">
        {% for review in product.reviews %}
            <div class="card mt-3" style="width: 100%;">
                <div class="card-body">
                    <p class="card-text text-right">
                        {% for i in 1..review.rating %}⭐
                        {% endfor %}
                    </p>
                    {% if review.user %}
                        <h4 class="card-title">{{review.user.username}}</h4>
                    {% else %}
                        <h4 class="card-title">{{review.mockUser}}</h4>
                    {% endif %}
                    <p class="card-text">{{review.body}}</p>
                    <p class="card-text text-right">
                        <small>{{review.createdAt | date("d/m/Y")}}</small>
                        {% if app.user and review.user == app.user %}
                            <button onclick="deleteReview({{review.id}})" class="mx-2 btn btn-danger btn-sm">Delete</button>
                        {% endif %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        const deleteReview = (reviewId) => {
            fetch (`/product/review/delete/${reviewId}`, {method: 'DELETE'}).then(res => {
                return res.json()
            }).then(jres => {
                alert(jres)
                window.location.href = window.location.href;
            })
        }
    </script>
{% endblock %}

templates/product/products.html.twig
{% extends "base.html.twig" %}
{% block title %}Products
{% endblock %}
{% block body %}
    <div class="row">
        {% for item in products %}
            <div class="col-4 mt-2" style="min-height: 573.6px;">
                <div class="card" style="min-height: 573.6px;">
                    <div class="card-body">
                        <img onclick="location.href='/product/{{item.id}}'" src="{{item.image}}?{{item.price}}" class="img-fluid mb-2" alt="{{item.title}}">
                        <h4 class="card-title">{{item.title}}</h4>
                        <p class="card-text">{{item.description}}</p>
                        <p class="card-text">{{item.price}}
                            $</p>
                        <button onclick="location.href='/cart/add/{{item.id}}'" class="btn btn-warning btn-sm">add to cart 🛒</button>
                        {# <button onclick="location.href='/product/{{item.id}}'" class="btn btn-primary btn-sm">View</button>
                        <button onclick="location.href='/product/edit/{{item.id}}'" class="btn btn-warning btn-sm mx-2">Edit</button>
                        <button onclick="deleteProduct({{item.id}})" class="btn btn-danger btn-sm">Delete</button> #}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/product/submit.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="row mb-2">
        <button type="button" onclick="window.history.back();" class="btn btn-secondary btn-sm btn-block mx-3">go back</button>
    </div>
    {{form_start(form)}}
    <div class="form-group">
        {{form_row(form.title, {"attr" : {"class" : "form-control "}})}}
    </div>
    <div class="form-group">
        {{form_row(form.description, {"attr" : {"class" : "form-control "}})}}
    </div>
    <div class="form-group">
        {{form_row(form.price, {"attr" : {"class" : "form-control "}})}}
    </div>
    <div
        class="form-group">
        {# {{form_row(form.image, {"attr" : {"class" : "form-control "}})}} #}
        <li class="form-text text-danger" id="selectImageError">
        {{form_row(form.image_File, {"attr" : {"class" : "form-control-file", 'hidden' : true, 'required' : false}})}}
        </li>
        <div class="form-group">
            <button type="button" onclick="selectImage()" id="btnSelect" class="btn btn-warning ">
                select image
            </button>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" name="btnSubmit" id="btnSubmit" class="btn btn-block {% if isEdit %} btn-warning {% else %}btn-primary{% endif %}" disabled>
            {% if isEdit %}
                Edit product
            {% else %}
                Add product
            {% endif %}
        </button>
    </div>
    {{form_end(form)}}
    <script>
        const selectImage = () => {
            const btnSubmit = document.getElementById('btnSubmit');
            const file = document.getElementById('product_image_File');
            file.click()
            btnSubmit.disabled = false;
        }
    </script>
{% endblock %}